name: photos
description: Photo gallery.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop: ^1.0.1-2.12.0-0
    
  rxdart: 0.26.0-nullsafety.1
  collections: 
    path: plugins/collections/build/collections

flutter:
  assets:
    - assets/photo_library-black-90dp.png

  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-BoldItalic.ttf
          style: italic
          weight: 700

    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700

    - family: IBM Plex Serif
      fonts:
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-BoldItalic.ttf
          style: italic
          weight: 700

    - family: mode
      fonts:
        - asset: fonts/mode.ttf

    - family: SharpMaterialIcons
      fonts:
        - asset: fonts/sharp_material_icons.ttf