library collections

interface Photos {
    pictures_directory: stream[PicturesDirectory],
    directory: (id: uuid) -> stream[DirectoryEntry],
    has_pictures: bool,
    image: (id: uuid) -> option[bytes],
    image_with_size: (id: uuid, witdh: int, heigth: int) -> stream[bytes],
    remove_image: (id: uuid),
}

struct PicturesDirectory {
    n_pictures: int,
    directory: DirectoryEntry,
}

type Directory {
    Picture: PictureEntry,
    Directory: DirectoryEntry,
}

struct PictureEntry {
    id: uuid,
    name: string,
    description: string,
    mime: string,
    width: int,
    height: int,
}

struct DirectoryEntry {
    id: uuid,
    name: string,
    items: Directory[],
    thumbnail: option[uuid],
    description: string,
}