library collections

interface Photos {
    directory: stream[DirectoryEntry],
    image: (id: uuid) -> stream[bytes],
    remove_image: (id: uuid) -> uuid,
    id: uuid,
}

type Directory {
    Picture: PictureEntry,
    Directory: DirectoryEntry,
}

struct PictureEntry {
    id: uuid,
    name: string,
    description: string,
    path: string,
    mime: string,
}

struct DirectoryEntry {
    id: uuid,
    items: Directory[],
    thumbnail: option[PictureEntry],
    description: string,
    name: string,
    path: string,
}